### ISSUE TITLE
`@contentful/field-editor-rich-text` adds newlines after ordered / unordered lists

### ISSUE THREAD

**Issue by erictraaaan** [contentful/field-editors#1561]
Hello,
We are noticing an issue with the Rich Text editor when using ordered / unordered lists.

If there is no text after the last element of a list, the editor will append a new line after the list (see screenshots).

This can also be seen in the API response when querying for this Contentful entry, as a new paragraph node is added, with no content.

Because of this, the consumers of this content end up displaying the empty paragraph tag as a new line, resulting in undesirable output of the rich text.

![Screenshot 2023-12-12 at 3 32 48 PM](https://github.com/contentful/field-editors/assets/16770078/850e8c9d-d8aa-4a40-a303-ba7926dfae57)

![image](https://github.com/contentful/field-editors/assets/16770078/60f52ef1-4cfe-4993-ad24-0ce69ea1b25a)

**Comment by z0al** [comment]
Hey, thanks for reporting. 

This is an intentional design decision to workaround a limitation in the internal framework. The team is aware of the issue and would like to explore possible solutions in the future, but I can't give an ETA as we have higher priority items. Btw, this also affect other block elements e.g. tables

In the meantime, you could remove the additional empty paragraph in your frontend when using one of the available [transformers](https://github.com/contentful/rich-text/tree/master/packages) e.g. `@contentful/rich-text-react-renderer`

I hope that helps.
