### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'type' in document for field RichText

### ISSUE THREAD

**Issue by fredericdevaux** [contentful/field-editors#715]
Hello,

First of all, thank you for your work on this library.

I have created a Contentful App that display fields conditionally in function of a select field. But everytime i try to edit a field  of type RichTextEditor, I have this error that is displayed : TypeError: Cannot use 'in' operator to search for 'type' in document (other fields that i tried are working fine).

Have you an idea if it comes from your library ?

Thanks

**Comment by nekosaur** [comment]
I am having the same issue. I am using the field like this.

```jsx
const contentfulField = sdk.entry.fields[field.id].getForLocale(locale);

...

<RichTextEditor sdk={{ ...sdk, field: contentfulField }} />
```

**Comment by waelhasan** [comment]
I have the same issue here: the rich text editor does not show the data coming from Contentful, and when i try to enter any thing in the rich text editor i have the error `TypeError: Cannot use 'in' operator to search for 'type' in document`.

I tried to take a look at the source code, and found out that the two issues comes from the way in which the `@contentful/contentful-slatejs-adapter` package is working; as it is the one that is used to translate the rich text content between `Contentful` and `Slatejs`. 
The issue is that in the function `toContentfulDocument` we iterate over the fields in the `document` object, which contains the field `type` that has the value `document`:
```json
{
  "type": "document"
}
```
then the function `isSlateElement` is called with `type` field as an argument:
```js
function isSlateElement(node) {
    return 'type' in node;
}
```

Which causes the error; as `in` can not be used on a string value like this:
```js
return 'type' in 'document'
```

I tried to play with the implementation to see if i can fix the issue, and managed to make the error disappear by changing the implementation of the function `toContentfulDocument` to be:
```js
....
flatmap(document.nodes, ...
...
```
Notice that my change is only using  `document.nodes` as an argument to `flatmap` function instead od `document`. 
That made the error disappear, but it does not save the correct value in `Contentful`'s entry.

I am not sure if what i have done is useful or not, but i surely hope to get this issue fixed soon :)

**Comment by cribbles** [comment]
Hi all

Thanks for bringing this to our attention. I believe this is due to an update in our rich text to slate format adapter library that was shipped recently. I'll make a task for our team to fix this library's version to the previous v14.1.2. Apologies for the disruption caused in the meantime.

Chris

**Comment by ayobami303** [comment]
any update on fixing this. it has reappeared again

**Comment by sssgordon** [comment]
It seems the fix is pushed but on npm it's still the last version (0.8.13), when is 0.8.14 dropping?

**Comment by cribbles** [comment]
@ayobami303 @sssgordon Apologies - looks like this was published with the wrong `dist/`. Would you please try with v`0.18.12` and report back if there are any issues?

**Comment by sssgordon** [comment]
@cribbles Thanks for the quick response, the problem still exists with `0.18.12` unfortunately.

**Comment by sssgordon** [comment]
@cribbles Thanks for the response, it seems rolling back to `0.8.12` for @contentful/field-editor-rich-text does the trick as in I can use the rich-text field and save it no problem!
